export enum CardRenderItemType {
  TEMPERATURE = 'temperature',
  OXYGEN = 'oxygen',
  WATER = 'water',
  PLANTS = 'plants',
  HEAT = 'heat',
  CREDITS = 'credits',
  CARDS = 'cards',
  SPACE = 'space',
  EARTH = 'earth',
  BUILDING = 'building',
  SCIENCE = 'science',
  NO_TAGS ='no_tags',
  CITY = 'city',
  GREENERY = 'greenery',
  TEXT = 'text',
  NBSP = 'nbsp',
  EMPTY_TILE = 'empty_tile',
  EMPTY_TILE_GOLDEN = 'empty_tile_golden',
  MULTIPLIER_WHITE = 'multiplier_white',
  PROJECT_REQUIREMENTS = 'project_requirements',
  AWARD = 'award',
  VP = 'vp',
  PLATE = 'plate',
}
