export enum CardName {
  // Standard Projects
  GAIN_1_CREDIT = 'Gain 1 Credit',
  PLACE_OR_RELOCATE_CITY = 'Place or Relocate City',
  PLACE_1_WATER_CUBE = 'Place 1 Water Cube',
  PLACE_1_GREENERY_CUBE = 'Place 1 Greenery Cube',
  GAIN_1_HEAT_CUBE = 'Place 1 Heat Cube',

  // Project Cards
  ICE_CAP_MELTING = 'Ice Cap Melting',
  POWER_GRID = 'Power Grid',
  RESEARCH_OUTPOST = 'Research Outpost',
  WINDMILLS = 'Windmills',
  SUBTERRANEAN_RESERVOIR = 'Subterranean Reservoir',
  INSECTS = 'Insects',
  LICHEN = 'Lichen',
  GREAT_DAM = 'Great Dam',
  ICE_ASTEROID = 'Ice Asteroid',
  FUSION_POWER = 'Fusion Power',
  BUSHES = 'Bushes',
  METHANE_FROM_TITAN = 'Methane From Titan',
  ALGAE = 'Algae',
  COMET = 'Comet',
  TREES = 'Trees',
  NUCLEAR_POWER = 'Nuclear Power',
  GHG_FACTORIES = 'GHG Factories',
  ASTEROID_MINING = 'Asteroid Mining',
  WATER_FROM_EUROPA = 'Water From Europa',
  LAVA_FLOWS = 'Lava Flows',
  ASTEROID = 'Asteroid',
  PROTECTED_VALLEY = 'Protected Valley',
  MOSS = 'Moss',
  AQUIFER_PUMPING = 'Aquifer Pumping',
  SOLAR_POWER = 'Solar Power',
  ARTIFICIAL_LAKE = 'Artificial Lake',
  GRASS = 'Grass',
  GEOTHERMAL_POWER = 'Geothermal Power',

  // Corporations
  GREEN_MARS = 'Green Mars',
  MARS_BANK = 'Mars Bank',
  PHOBOS_FIRST = 'Phobos First',
  ZEUS_POWER = 'Zeus Power',
  MINERS_UNION = 'Miner\'s Union',
  INNOVATIVE_SOLUTIONS = 'Innovative Solutions',
  CRUSOE_ENTERPRISE = 'Crusoe Enterprise',
  VERIDIAN_INTERGALACTIC = 'Veridian Intergalactic',
  SOL_INVICTUS = 'Sol Invictus',
  UN_TERRAFORMING_PROGRAMME = 'U.N. Terraforming Programme',

  // Awards
  DRY_HEAT = 'Dry Heat',
  CAPITAL_CITY = 'Capital City',
  SOUTHERN_CHARM = 'Southern Charm',
  YANKEE_DOODLE = 'Yankee Doodle',
  WATERFRONT_PROPERTY = 'Waterfront Property',
  CABIN_IN_THE_WOODS = 'Cabin in the woods',

  // Milestones
  DISCOUNTER = 'Discounter',
  JACK_OF_ALL_TRADES = 'Jack of All Trades',
  MUILTITASKER = 'Multitasker',
  EXPLORER = 'Explorer',
  CHARGER = 'Charger',
  COLLECTOR = 'Collector',
}
